% processAdvisorExampleStart
% copyfile('C:\Users\ahmedh\MATLAB\Projects\examples\ProcessAdvisorExample246', 'D:\sb\ws\')
projectBase = openProject('D:\\repos\\gh\\padv25aExample');

os = "win";						% win / linux
ShellEnvironment = "pwsh";		% pwsh / bash

runProcessOptions = padv.pipeline.RunProcessOptions();
runProcessOptions.set("GenerateJUnitForProcess", true);
runProcessOptions.set("ExitInBatchMode", false);
% padv.internal.FeatureManager.set('PipelineParallelBranchMerger', true)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			SingleStage
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
op = padv.pipeline.JenkinsOptions( ...
		"PipelineArchitecture", "SingleStage", ...
		"RunprocessCommandOptions", runProcessOptions, ...
		"ShellEnvironment", ShellEnvironment, ...
		"AgentLabel", strcat("padv_",os,"_agents"), ...
		"EnableIncrementalRunprocess", false, ...
		"GeneratedPipelineDirectory", strcat("pipelines/",os,"/SingleStage"), ...
		"GeneratedJenkinsFileName", "Jenkinsfile_sl");

padv.pipeline.generatePipeline(op);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			SingleStage - Executors
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
op = padv.pipeline.JenkinsOptions( ...
			"PipelineArchitecture", "SingleStage", ...
			"RunprocessCommandOptions", runProcessOptions, ...
			"ShellEnvironment", ShellEnvironment, ...
			"AgentLabel", strcat("padv_",os,"_agents"), ...
			"UseSameExecutorForSequentialStages", false,...
			"EnableIncrementalRunprocess", false, ...
			"GeneratedPipelineDirectory", strcat("pipelines/",os,"/SingleStage"), ...
			"GeneratedJenkinsFileName", "Jenkinsfile_sl_Executors");

padv.pipeline.generatePipeline(op);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			SerialStagesGroupPerTask
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
op = padv.pipeline.JenkinsOptions( ...
		"PipelineArchitecture", "SerialStagesGroupPerTask", ...
		"RunprocessCommandOptions", runProcessOptions, ...
		"ShellEnvironment", ShellEnvironment, ...
		"AgentLabel", strcat("padv_",os,"_agents"), ...
		"GeneratedPipelineDirectory", strcat("pipelines/",os,"/SerialStagesGroupPerTask"), ...
		"GeneratedJenkinsFileName", "Jenkinsfile_sl");

padv.pipeline.generatePipeline(op);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			SerialStagesGroupPerTask - Executors
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
op = padv.pipeline.JenkinsOptions( ...
		"PipelineArchitecture", "SerialStagesGroupPerTask", ...
		"RunprocessCommandOptions", runProcessOptions, ...
		"ShellEnvironment", ShellEnvironment, ...
		"AgentLabel", strcat("padv_",os,"_agents"), ...
		"UseSameExecutorForSequentialStages", false,...
		"StopOnStageFailure", true, ...
		"EnableIncrementalRunprocess", false, ...
		"GeneratedPipelineDirectory", strcat("pipelines/",os,"/SerialStagesGroupPerTask"), ...
		"GeneratedJenkinsFileName", "Jenkinsfile_sl_Executors");

padv.pipeline.generatePipeline(op);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			SerialStages
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
op = padv.pipeline.JenkinsOptions( ...
		"PipelineArchitecture", "SerialStages", ...
		"RunprocessCommandOptions", runProcessOptions, ...
		"ShellEnvironment", ShellEnvironment, ...
		"AgentLabel", strcat("padv_",os,"_agents"), ...
		"GeneratedPipelineDirectory", strcat("pipelines/",os,"/SerialStages"), ...
		"GeneratedJenkinsFileName", "Jenkinsfile_sl");

padv.pipeline.generatePipeline(op);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			SerialStages - Executors
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
op = padv.pipeline.JenkinsOptions( ...
		"PipelineArchitecture", "SerialStages", ...
		"RunprocessCommandOptions", runProcessOptions, ...
		"ShellEnvironment", ShellEnvironment, ...
		"AgentLabel", strcat("padv_",os,"_agents"), ...
		"UseSameExecutorForSequentialStages", false,...
		"EnableIncrementalRunprocess", true, ...
		"GeneratedPipelineDirectory", strcat("pipelines/",os,"/SerialStages"), ...
		"GeneratedJenkinsFileName", "Jenkinsfile_sl_Executors");

padv.pipeline.generatePipeline(op);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			IndependentModelPipelines
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
op = padv.pipeline.JenkinsOptions( ...
		"PipelineArchitecture", "IndependentModelPipelines", ...
		"RunprocessCommandOptions", runProcessOptions, ...
		"ShellEnvironment", ShellEnvironment, ...
		"AgentLabel", strcat("padv_",os,"_agents"), ...
		"GeneratedPipelineDirectory", strcat("pipelines/",os,"/IndependentModelPipelines"), ...
		"GeneratedJenkinsFileName", "Jenkinsfile_sl");

padv.pipeline.generatePipeline(op);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			IndependentModelPipelines - Executors
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
op = padv.pipeline.GitHubOptions( ...
		"PipelineArchitecture", "IndependentModelPipelines", ...
		"RunprocessCommandOptions", runProcessOptions, ...
		"ShellEnvironment", ShellEnvironment, ...
		"AgentLabel", strcat("padv_",os,"_agents"), ...
		"UseSameExecutorForSequentialStages", false,...
		"StopOnStageFailure", true, ...
		"EnableIncrementalRunprocess", true, ...
		"GeneratedPipelineDirectory", strcat("pipelines/",os,"/IndependentModelPipelines"), ...
		"GeneratedJenkinsFileName", "Jenkinsfile_sl_Executors_merge");
padv.pipeline.generatePipeline(op);

op = padv.pipeline.GitHubOptions( ...
		"PipelineArchitecture", "IndependentModelPipelines", ...
		"RunprocessCommandOptions", runProcessOptions, ...
		"ShellEnvironment", ShellEnvironment, ...
		"RunnerLabels", strcat("padv_",os,"_agents"), ...
		"MatlabInstallationLocation", "${{ vars.PATH_TO_MATLAB }}", ...
		"StopOnStageFailure", true, ...
		"EnableIncrementalRunprocess", false, ...
		"GeneratedPipelineDirectory", strcat(".github/workflows/"), ...
		"GeneratedYMLFileName", strcat(os,"_IndependentModelPipelines_MultiExecutors.yaml"));

padv.pipeline.generatePipeline(op);

% ------------------------- Add pipeline name
ymlFiles = dir(fullfile(currentProject().RootFolder ,'pipelines/**/Jenkinsfile_sl*'));
for k = 1:length(ymlFiles)
    filePath = fullfile(ymlFiles(k).folder, ymlFiles(k).name);
	fid = fopen(filePath, 'r');
	fileContents = textscan(fid, '%s', 'Delimiter', '\n', 'Whitespace', '');
	fileContents = strjoin(fileContents{:}, newline);
	fclose(fid);
	if startsWith(fileContents, "pipeline{" + newline + "    agent none")
		fid = fopen(filePath, 'w');
		fileContents = strrep(fileContents, "pipeline{" + newline + "    agent none", '');
		fileContents = strrep(fileContents, "\$", '\\$');
		fileContents = "pipeline{" + newline + "    agent{label('padv_win_agents')}" + newline ...
			+ "    environment{PATH=""${env.JENKINS_WIN_MATLAB_PATH};${env.PATH}""}" + fileContents;
		fprintf(fid, fileContents);
		fclose(fid);
	end
end