//Scripted Pipeline
node('padv_win_agents') {
		stage('Git_Clone'){
		    git branch: 'main',
            url: 'https://github.mathworks.com/ahmedh/padv24bExample.git'
		}

        // Requires MATLAB plugin
		stage('Pipeline Generation'){
            env.PATH = "${env.JENKINS_WIN_MATLAB_PATH};${env.PATH}"
            env.PipelineArchitecture = "IndependentModelPipelines"
            env.JenkinsOS = "win"
            env.ShellEnvironment = "pwsh"
            
            echo 'Pipeline generation stage logic'
            /* Open the project and generate the pipeline using
            appropriate options */
            // SingleStage, SerialStages, SerialStagesGroupPerTask, IndependentModelPipelines
            runMATLABCommand """padv.internal.FeatureManager.set('PipelineParallelBranchMerger', true); cp = openProject(pwd);
                rpo = padv.pipeline.RunProcessOptions();
                rpo.set("GenerateJUnitForProcess", true);
                rpo.set("ExitInBatchMode", false);
                padv.pipeline.generatePipeline(...
                    padv.pipeline.JenkinsOptions(...
                        RunprocessCommandOptions= rpo,...
                        AgentLabel = strcat("padv_", "${env.JenkinsOS}" ,"_agents"),...
                        ShellEnvironment = "${env.ShellEnvironment}",...
                        StopOnStageFailure = true,...
                        EnableIncrementalRunprocess = false, ...
                        PipelineArchitecture = padv.pipeline.Architecture.${env.PipelineArchitecture},...
                        GeneratedJenkinsFileName = "simulink_pipeline",...
                        GeneratedPipelineDirectory = fullfile("derived","pipeline"),...
                        UseSameExecutorForSequentialStages = false));"""
		}
        
        // pass necessary environment variables to generated pipeline
        withEnv(["PATH=${env.JENKINS_WIN_MATLAB_PATH};${env.PATH}"]) {    
            /* This file is generated automatically by 
            padv.pipeline.generatePipeline with a default name 
            of simulink_pipeline. Update this field if the 
            name or location of the generated pipeline file is changed */
            rootDir = pwd()

            load "${rootDir}/derived/pipeline/simulink_pipeline"
        }
}